fixed combination of 'extern' and 'inline' for some functions changes 	modified:   build 	renamed:    inc/misc.c -> inc/misc.h 	deleted:    inc/terminal_color.c 	modified:   inc/terminal_color.h

diff --git a/source/build b/source/build
--- a/source/build
+++ b/source/build
@@ -1,26 +1,46 @@
-SRCS="main.c inc/terminal_color.o inc/misc.o"
+MAIN="main.c"
+SRCS=( )
+ALLINC=""
 
-HELP="Usage: build [<options>]
-    clear               delete build binarys
-    check               check for compilation
-    debug               pass _DEBUG macro into code & compile"
+
+HELP="Usage: build [<options>] \n
+    clear ---------- delete build binarys\n
+    check ---------- check for compilation\n
+    debug ---------- pass _DEBUG macro into code & compile\n
+    help ----------- show current help message"
+
+function BuildIncludes() {
+  for name in ${SRCS[@]}; do
+    echo "---Building $name---"
+    gcc -O3 -c inc/$name.c -o ./objs/$name.o
+    if [ $? -ne 0 ]; then
+      echo "---Building $name Failed---"
+      exit 1
+    fi;
+  done;
+}
 
 function RegularBuild() {
-  gcc -O3 -o bytion $SRCS -Wextra
+  BuildIncludes
+  if [ $? -ne 0 ]; then
+    exit 1
+  fi
+  echo "---Building Bytion---"
+  gcc -O3 -o bytion $MAIN
   if [ $? -eq 0 ]; then
     echo "---Build successfull---"
   fi
 }
 
 function  DebugBuild() {
-  gcc -D_DEBUG -o bytion $SRCS -Wextra
+  gcc -D_DEBUG -o bytion $MAIN $ALLINC -Wextra
   if [ $? -eq 0 ]; then
     echo "---Debug build successfull---"
   fi
 }
 
 function CheckBuild() {
-  gcc -o temp.check.build $SRCS -Wextra
+  gcc -o temp.check.build $MAIN $ALLINC -Wextra
   if [ $? -eq 0 ]; then
     echo "---Build check successfull---"
     rm temp.check.build
@@ -40,9 +60,12 @@ elif [ $# -eq 1 ]; then
     clear)
       rm -i bytion
       ;;
-    *)
-      echo "'$1' is not an option" $'\n'
+    help)
       echo $HELP
+      ;;
+    *)
+      printf "'$1' is not an option\n"
+      echo -e $HELP
       ;;
   esac
 else
